### ISSUE TITLE
Mod Crashes on 1.20.1

### ISSUE THREAD

**Issue by Edgryphon** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#100]
First i thought it might be some incompatability with some other mods, but then i ran the game with just the Fabric Api and Galaxies: Parzi's Star Wars Mod and it still crashed. This leads me to belive it is some sort of issue with this version of the mod.

This was using 0.0.109 version of the mod

Here's the crashreport:
[crash-2024-02-27_13.23.26-client.txt](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/files/14419463/crash-2024-02-27_13.23.26-client.txt)

**Comment by parzivail** [comment]
1.20.1 is unsupported due to an issue with Fabric, please update to 1.20.2.
