### ISSUE TITLE
Incompatible with Sodium in 1.20.2

### ISSUE THREAD

**Issue by Edgryphon** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#101]
basically closes the game as soon as the loading bar ticks the slightest bit. I checked, but there are no crashrepports anywhere (they are enabled). So i can sadly not provide any specific details, but the mod works fine on its own (with the fabric Api of cause), and sodium also works fine (even with other mods), just those two (Sodium and GalaxiesParzisstarwarsmod) for some reason cause the game to freak out during initialisation.

**Comment by parzivail** [comment]
Indium is required when using Sodium.

**Comment by Edgryphon** [comment]
That did the trick! now i can finally enjoy your awsome mod!
