### ISSUE TITLE
Will this mod ever get planets?

### ISSUE THREAD

**Issue by ghost** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#104]
There are no planets in the base mod. And it's weird needing addons to add them. Parzi's Star Wars Mod 1.7.10 had them? Consider what it shows in the pictures? 
**Theres Supposed To Be Planets**
![Screenshot 2024-06-02 194433](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/assets/166317640/ca0469bd-c0b2-42b4-b4b3-b999d9999d66)

**Comment by Coda1552** [comment]
Wait this guy is spitting facts tho

**Comment by SpoderMan3288** [comment]
Man shut yo bitch ass the mod is still a work in progress and tatooine is literally in it already

**Comment by reverentfeynmen** [comment]
> Man shut yo **** *** the mod is still a work in progress and tatooine is literally in it already

I didn't relise that until after I posted the issue.

**Comment by reverentfeynmen** [comment]
> Wait this guy is spitting facts tho

What do you mean facts?

**Comment by reverentfeynmen** [comment]
If people keep swearing in this issue. I'm gona have to close it.

**Comment by Coda1552** [comment]
Facts.
