### ISSUE TITLE
game crashes on startup and the issue seems to be the mod itself

### ISSUE THREAD

**Issue by DARKLOL680** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#108]
For some reasons the log says the mod is running on Forge despite it being for Fabric

![image](https://github.com/user-attachments/assets/80bd7ddf-685f-41c7-b45d-799ecd807277)

**Comment by parzivail** [comment]
Upload your crash log

**Comment by DARKLOL680** [comment]
[latest.log](https://github.com/user-attachments/files/17980018/latest.log)

**Comment by parzivail** [comment]
I don't see a crash in that log. However, the warning you posted is unrelated and is due to `creativecore` depending on `net_minecraftforge_eventbus`. Try again with only PSWG and Fabric API installed and see if you have the same issue.

**Comment by DARKLOL680** [comment]
ok it did work with only PSWG and Fabric API but my modpack still crashes after removing Creative core and the mods that requires it
so PSGW shouldn't be the issue now

**Comment by parzivail** [comment]
Glad to hear it.
