### ISSUE TITLE
Can not be used normally

### ISSUE THREAD

**Issue by taiwan-king** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#47]
There is a problem with cross-center aiming and distance determination.
MC version 1.17

**Comment by parzivail** [comment]
Can you elaborate a little more on that the issue is please?

**Comment by taiwan-king** [comment]
https://www.youtube.com/watch?v=wJdpqVkXmeQ

**Comment by parzivail** [comment]
Thanks for the report! This is fixed in the next alpha, and was fixed by commit ID d7b75b8eb76fb525495b7a01c493506b871b8f63
