### ISSUE TITLE
1.17 Crash When Firing Guns

### ISSUE THREAD

**Issue by lartts** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#48]
Log:
[latest.log](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/files/7060103/latest.log)

Mod Version:
0.0.42+1.17.1

Fabric Version:
0.11.6

**Comment by ShadowSlayerFX1** [comment]
this also happens with 1.18.1 versions
