### ISSUE TITLE
Lightsabers bug with shaders

### ISSUE THREAD

**Issue by Niketats** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#59]
![image](https://user-images.githubusercontent.com/68917520/159381255-f041f457-a3d2-4de4-abb6-bc123818c808.png)
![image](https://user-images.githubusercontent.com/68917520/159381277-c80f5fed-9728-4af2-9689-3af0dbedd902.png)

**Comment by parzivail** [comment]
We're currently working with coderbot to resolve this issue, but it's going to take a few updates unfortunately

**Comment by parzivail** [comment]
Fixed in Iris
