### ISSUE TITLE
Only the half of the mod

### ISSUE THREAD

**Issue by DerSith** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#79]
Idk. i only have the half of the mod on my server. i dont have any starfighters or quests(i read something about quests) and i dont have any planets

**Comment by parzivail** [comment]
Only like half of the mod has been implemented

To get to Tatooine, use the command: `/cdim pswg:tatooine`

For further questions, please join [the Discord](https://discord.pswg.dev)
