### ISSUE TITLE
1.20.1 Crash on World Load

### ISSUE THREAD

**Issue by Gamerbolts** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#80]
I am creating a modpack and when I tried loading into the world it popped up a message saying PSWG has crashed and so send the notice, but wanted to post here as well. Here is the crashlog and log

[crash-2023-06-28_14.23.28-server.txt](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/files/11899302/crash-2023-06-28_14.23.28-server.txt)
[latest.log](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/files/11899304/latest.log)

I am using PSWG v0.0.109

**Comment by parzivail** [comment]
Can you please try to reproduce this issue with only PSWG and Fabric API installed? If the issue goes away, please try to narrow down which mod causes it.

**Comment by Gamerbolts** [comment]
Thanks for responding. I was testing some more and seems like it may be better furnaces reforged or factory api. But PSWG is in my pack now and it is working!
