### ISSUE TITLE
проблема с вязи с новым обновлениями ядра фабрика. нужно мод переписать под новое ядро на версию 1.19.2 

### ISSUE THREAD

**Issue by Chniper** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#83]
состовляет ошибку в маине. вызывает ошибку вылит из игры у меня повышенная версия ядра и версия 1.19.2 версия маина. это мой любимы мод на зв и пожалуста допилите для версии 1.19.2 что бы дополнить нормальную сборку с вашим модом.вообщем сделайте по красате пожалуста.

**Comment by parzivail** [comment]
Please update to 1.20.2.
