### ISSUE TITLE
1.20.1 Crash on Launch

### ISSUE THREAD

**Issue by Hexblood** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#90]
Minecraft: 1.20.1
Loader: Fabric 0.15.0
Fabric API: 0.91.0
PSWG: 0.0.109

I am getting this crash on launch. I did see in another post that Indium might be a problem so disabled it. Still getting a crash. Looks to be the same error with and without Indium. 

Crash is before the MC window opens.

Crash Report: https://pastebin.com/umG2YmVg

**Comment by parzivail** [comment]
This is an issue with that particular version of Fabric API. I recommend you update to 1.20.2 with the latest version of everything, or else use Fabric API 0.14.22

**Comment by Hexblood** [comment]
Ah OK. thanks for the info. Only reason I have not gone to 1.20.2 yet is I am waiting for other mods. Might just have to suck it up and play w/o them LOL.
