### ISSUE TITLE
1.20.1 Client Crash

### ISSUE THREAD

**Issue by Gamerbolts** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#92]
Hello!

I am creating a modpack for 1.20.1 and while the client was loading it crashed.

The crashlog
[crash-2024-01-03_14.52.49-client.txt](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/files/13823319/crash-2024-01-03_14.52.49-client.txt)

the normal log
[latest.log](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/files/13823321/latest.log)

Any help is appreciated. Thank you!

**Comment by parzivail** [comment]
This is a bug caused by a particular version of Fabric Loader. Please either downgrade Fabric Loader or upgrade PSWG to a 1.20.2+ version.

**Comment by Gamerbolts** [comment]
Downgrading breaks some mods and upgrading is an issue because other mods have not updated to 1.20.2 :(

**Comment by parzivail** [comment]
Unfortunately, I can't help with that.

**Comment by Gamerbolts** [comment]
Noticed Fabric 1.20.1 updated to 0.15.6, but still getting a crash. This updated fixed a lot of other mods from crashing but PSWG still crashes :( here is the log and crash log if anything is different

[latest.log](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/files/14011456/latest.log)
[crash-2024-01-22_08.33.55-client.txt](https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/files/14011453/crash-2024-01-22_08.33.55-client.txt)

**Comment by parzivail** [comment]
The issue that Fabric introduced has not been, and will not be, reverted. Therefore only old versions of Fabric Loader will work for 1.20.1. We do not support 1.20.1 anymore.
